<a href="https://colab.research.google.com/github/kendall5410/nanoGPT/blob/main/Erics_Techx_2024_nanoGPT.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print("Hello Tech exchange")

Hello Tech exchange


get the data


In [2]:
!wget http://gir.fyi/techx/input.txt

--2024-05-15 19:03:20--  http://gir.fyi/techx/input.txt
Resolving gir.fyi (gir.fyi)... 216.239.34.21, 216.239.32.21, 216.239.38.21, ...
Connecting to gir.fyi (gir.fyi)|216.239.34.21|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt [following]
--2024-05-15 19:03:21--  https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1115394 (1.1M) [text/plain]
Saving to: ‘input.txt’

input.txt           100%[===================>]   1.06M  --.-KB/s    in 0.007s  

2024-05-15 19:03:21 (150 MB/s) - ‘input.txt’ saved [1115394/1115394]



In [3]:
with open('input.txt','r', encoding='utf-8') as f:
  raw_training_data = f.read()
print(len(raw_training_data))

1115394


In [4]:
len(set(raw_training_data))

65

In [5]:
''.join(sorted(set(raw_training_data)))

"\n !$&',-.3:;?ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz"

In [7]:
from collections import defaultdict

freqs = defaultdict(int)

for letter in raw_training_data:
  freqs[letter] += 1

freqs

defaultdict(int,
            {'F': 1797,
             'i': 45537,
             'r': 48889,
             's': 49696,
             't': 67009,
             ' ': 169892,
             'C': 3820,
             'z': 356,
             'e': 94611,
             'n': 48529,
             ':': 10316,
             '\n': 40000,
             'B': 2761,
             'f': 15770,
             'o': 65798,
             'w': 17585,
             'p': 10808,
             'c': 15623,
             'd': 31358,
             'a': 55507,
             'y': 20448,
             'u': 26584,
             'h': 51310,
             ',': 19846,
             'm': 22243,
             'k': 7088,
             '.': 7885,
             'A': 7819,
             'l': 33339,
             'S': 4523,
             'Y': 1718,
             'v': 7793,
             '?': 2462,
             'R': 4869,
             'M': 2840,
             'W': 3530,
             "'": 6187,
             'L': 3876,
             'I': 11832,
             'N': 5079,

In [10]:
import random

SAMPLE_SIZE = 500
training_data_size = len(raw_training_data)
start = random.randrange(0, training_data_size - SAMPLE_SIZE)
print(raw_training_data[start:start+SAMPLE_SIZE])

:
Nay, it is ten times true; for truth is truth
To the end of reckoning.

DUKE VINCENTIO:
Away with her! Poor soul,
She speaks this in the infirmity of sense.

ISABELLA:
O prince, I conjure thee, as thou believest
There is another comfort than this world,
That thou neglect me not, with that opinion
That I am touch'd with madness! Make not impossible
That which but seems unlike: 'tis not impossible
But one, the wicked'st caitiff on the ground,
May seem as shy, as grave, as just, as absolute
As An


Data Preparation

In [12]:
tokens = ''.join(sorted(set(raw_training_data)))
token_to_number = {t: i for i, t in enumerate(tokens)}
token_to_number

{'\n': 0,
 ' ': 1,
 '!': 2,
 '$': 3,
 '&': 4,
 "'": 5,
 ',': 6,
 '-': 7,
 '.': 8,
 '3': 9,
 ':': 10,
 ';': 11,
 '?': 12,
 'A': 13,
 'B': 14,
 'C': 15,
 'D': 16,
 'E': 17,
 'F': 18,
 'G': 19,
 'H': 20,
 'I': 21,
 'J': 22,
 'K': 23,
 'L': 24,
 'M': 25,
 'N': 26,
 'O': 27,
 'P': 28,
 'Q': 29,
 'R': 30,
 'S': 31,
 'T': 32,
 'U': 33,
 'V': 34,
 'W': 35,
 'X': 36,
 'Y': 37,
 'Z': 38,
 'a': 39,
 'b': 40,
 'c': 41,
 'd': 42,
 'e': 43,
 'f': 44,
 'g': 45,
 'h': 46,
 'i': 47,
 'j': 48,
 'k': 49,
 'l': 50,
 'm': 51,
 'n': 52,
 'o': 53,
 'p': 54,
 'q': 55,
 'r': 56,
 's': 57,
 't': 58,
 'u': 59,
 'v': 60,
 'w': 61,
 'x': 62,
 'y': 63,
 'z': 64}

In [15]:
number_to_token = {i: t for i, t in enumerate(tokens)} #mapping each token to its corresponding token
number_to_token

{0: '\n',
 1: ' ',
 2: '!',
 3: '$',
 4: '&',
 5: "'",
 6: ',',
 7: '-',
 8: '.',
 9: '3',
 10: ':',
 11: ';',
 12: '?',
 13: 'A',
 14: 'B',
 15: 'C',
 16: 'D',
 17: 'E',
 18: 'F',
 19: 'G',
 20: 'H',
 21: 'I',
 22: 'J',
 23: 'K',
 24: 'L',
 25: 'M',
 26: 'N',
 27: 'O',
 28: 'P',
 29: 'Q',
 30: 'R',
 31: 'S',
 32: 'T',
 33: 'U',
 34: 'V',
 35: 'W',
 36: 'X',
 37: 'Y',
 38: 'Z',
 39: 'a',
 40: 'b',
 41: 'c',
 42: 'd',
 43: 'e',
 44: 'f',
 45: 'g',
 46: 'h',
 47: 'i',
 48: 'j',
 49: 'k',
 50: 'l',
 51: 'm',
 52: 'n',
 53: 'o',
 54: 'p',
 55: 'q',
 56: 'r',
 57: 's',
 58: 't',
 59: 'u',
 60: 'v',
 61: 'w',
 62: 'x',
 63: 'y',
 64: 'z'}

In [16]:
def encode(s):
  return_value = []
  for character in s:
    return_value.append(token_to_number[character])
  return return_value
encode("Tech Exhange")

[32, 43, 41, 46, 1, 17, 62, 46, 39, 52, 45, 43]

In [17]:
def decode(nums):
  return ''.join([number_to_token[n] for n in nums ])
decode(encode("Tech Exchange"))

'Tech Exchange'

In [18]:
import torch

data = torch.tensor(encode(raw_training_data), dtype=torch.long)
data

tensor([18, 47, 56,  ..., 45,  8,  0])

In [19]:
holdout_size = int(0.1 * len(data))
holdout_size

111539

In [20]:
test_data = data[:holdout_size]
training_data = data[holdout_size:]
len(test_data), len(training_data)

(111539, 1003855)

In [22]:
BLOCK_SIZE = 8
training_data[:BLOCK_SIZE+1]

tensor([43, 58,  6,  1, 25, 39, 56, 41, 47])

In [90]:
start_from = random.randint(0, training_data_size-BLOCK_SIZE)
decode(training_data[start_from:start_from+BLOCK_SIZE].tolist())


' I have '

In [91]:
x = training_data[:BLOCK_SIZE]
y = training_data[1:BLOCK_SIZE+1]
for t in range(BLOCK_SIZE):
  context = x[:t+1]
  target = y[t]
  print(f"in: {context}, out: {target}")

in: tensor([43]), out: 58
in: tensor([43, 58]), out: 6
in: tensor([43, 58,  6]), out: 1
in: tensor([43, 58,  6,  1]), out: 25
in: tensor([43, 58,  6,  1, 25]), out: 39
in: tensor([43, 58,  6,  1, 25, 39]), out: 56
in: tensor([43, 58,  6,  1, 25, 39, 56]), out: 41
in: tensor([43, 58,  6,  1, 25, 39, 56, 41]), out: 47


In [92]:
torch.manual_seed(1337)

BATCH_SIZE = 4

In [96]:
def get_batch(split):
  data = training_data if split == 'train' else test_data
  ix = torch.randint(len(data) - BLOCK_SIZE, (BATCH_SIZE,))
  #print(ix)
  x = torch.stack([data[i:i+BLOCK_SIZE] for i in ix])
  y = torch.stack([data[i+1:i+BLOCK_SIZE+1] for i in ix])
  return x, y

get_batch('train')


(tensor([[37, 53, 59,  1, 46, 39, 60, 43],
         [ 1, 58, 46, 47, 57, 12,  0,  0],
         [ 6,  1, 58, 46, 43, 52,  1, 13],
         [47, 57,  1, 46, 43, 52, 41, 43]]),
 tensor([[53, 59,  1, 46, 39, 60, 43,  1],
         [58, 46, 47, 57, 12,  0,  0, 28],
         [ 1, 58, 46, 43, 52,  1, 13, 50],
         [57,  1, 46, 43, 52, 41, 43, 12]]))

In [97]:
xb, yb = get_batch('train')
for b in range(BATCH_SIZE):
  for t in range(BLOCK_SIZE):
    context = xb[b, :t+1]
    target = yb[b,t]
    print(f'input {context.tolist()}, target {target}')

input [1], target 39
input [1, 39], target 52
input [1, 39, 52], target 1
input [1, 39, 52, 1], target 43
input [1, 39, 52, 1, 43], target 51
input [1, 39, 52, 1, 43, 51], target 54
input [1, 39, 52, 1, 43, 51, 54], target 58
input [1, 39, 52, 1, 43, 51, 54, 58], target 63
input [24], target 47
input [24, 47], target 44
input [24, 47, 44], target 43
input [24, 47, 44, 43], target 1
input [24, 47, 44, 43, 1], target 39
input [24, 47, 44, 43, 1, 39], target 52
input [24, 47, 44, 43, 1, 39, 52], target 42
input [24, 47, 44, 43, 1, 39, 52, 42], target 1
input [46], target 47
input [46, 47], target 57
input [46, 47, 57], target 6
input [46, 47, 57, 6], target 1
input [46, 47, 57, 6, 1], target 39
input [46, 47, 57, 6, 1, 39], target 52
input [46, 47, 57, 6, 1, 39, 52], target 42
input [46, 47, 57, 6, 1, 39, 52, 42], target 1
input [59], target 56
input [59, 56], target 1
input [59, 56, 1], target 50
input [59, 56, 1, 50], target 43
input [59, 56, 1, 50, 43], target 39
input [59, 56, 1, 50, 

In [98]:
import torch
import torch.nn as nn
from torch.nn import functional as F

In [99]:
class BigramLanguageModel(nn.Module):

  def __init__(self, vocab_size):
    super().__init__()
    self.token_embedding_table = nn.Embedding(vocab_size, vocab_size)
